from __future__ import annotations

import json
import zipfile
from collections import Counter
from datetime import datetime, timezone
from decimal import Decimal
from pathlib import Path
from typing import Callable, Iterable

from openpyxl import Workbook
from openpyxl.cell import Cell
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.dimensions import ColumnDimension
from openpyxl.worksheet.worksheet import Worksheet

from .constants import (
    APP_NAME,
    APP_VERSION,
    BLACK,
    DATE_FORMAT,
    GREEN,
    GREY,
    LIGHT_GREY,
    NAVY,
    NAVY_LIGHT,
    NUMBER_FORMAT,
    ORANGE,
    RED,
    WHITE,
    YELLOW,
    YELLOW_LIGHT,
)
from .models import (
    GenerationResult,
    Issue,
    LedgerRow,
    ReportBundle,
    StatementRow,
    TrialBalanceRow,
    ZERO,
)
from .utils import safe_excel_text, slugify

THIN_GREY = Side(style="thin", color="B7C9D6")
MEDIUM_NAVY = Side(style="medium", color=NAVY)
DOUBLE_NAVY = Side(style="double", color=NAVY)

MONTHS_ID = [
    "Januari",
    "Februari",
    "Maret",
    "April",
    "Mei",
    "Juni",
    "Juli",
    "Agustus",
    "September",
    "Oktober",
    "November",
    "Desember",
]


def _num(value: Decimal | int | float | None) -> float | int | None:
    if value is None:
        return None
    if isinstance(value, Decimal):
        return float(value)
    return value


def _period_label(bundle: ReportBundle) -> str:
    start = bundle.period_start
    end = bundle.period_end
    if start.day == 1 and end.month == 12 and end.day == 31 and start.year == end.year:
        return f"{MONTHS_ID[start.month - 1]} - {MONTHS_ID[end.month - 1]} {end.year}"
    if start.month == end.month and start.year == end.year:
        return f"{start.day} - {end.day} {MONTHS_ID[end.month - 1]} {end.year}"
    return (
        f"{start.day} {MONTHS_ID[start.month - 1]} {start.year} - "
        f"{end.day} {MONTHS_ID[end.month - 1]} {end.year}"
    )


def _set_document_properties(workbook: Workbook, title: str) -> None:
    workbook.properties.title = title
    workbook.properties.subject = "Generated accounting report"
    workbook.properties.creator = APP_NAME
    workbook.properties.keywords = "accounting, financial statements, trial balance"
    workbook.properties.description = f"Generated by {APP_NAME} v{APP_VERSION}"


def _title_rows(worksheet: Worksheet, bundle: ReportBundle, title: str, last_column: int) -> None:
    worksheet.merge_cells(start_row=1, start_column=1, end_row=1, end_column=last_column)
    worksheet.merge_cells(start_row=2, start_column=1, end_row=2, end_column=last_column)
    worksheet.merge_cells(start_row=3, start_column=1, end_row=3, end_column=last_column)
    worksheet["A1"] = safe_excel_text(bundle.client_name)
    worksheet["A2"] = safe_excel_text(title)
    worksheet["A3"] = f"Periode / Period : {_period_label(bundle)}"
    for row in range(1, 4):
        cell = worksheet.cell(row=row, column=1)
        cell.font = Font(name="Aptos", size=12 if row == 1 else 11, bold=True, color=BLACK)
        cell.alignment = Alignment(horizontal="left", vertical="center")
    worksheet.row_dimensions[1].height = 22
    worksheet.row_dimensions[2].height = 20
    worksheet.row_dimensions[3].height = 20


def _style_header(worksheet: Worksheet, row: int, columns: int, *, yellow: bool = False) -> None:
    fill = PatternFill("solid", fgColor=YELLOW if yellow else NAVY)
    font_color = BLACK if yellow else WHITE
    for col in range(1, columns + 1):
        cell = worksheet.cell(row=row, column=col)
        cell.fill = fill
        cell.font = Font(name="Aptos", size=10, bold=True, color=font_color)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = Border(top=MEDIUM_NAVY, bottom=MEDIUM_NAVY)
    worksheet.row_dimensions[row].height = 30


def _apply_numeric_format(worksheet: Worksheet, rows: Iterable[int], columns: Iterable[int]) -> None:
    for row in rows:
        for col in columns:
            cell = worksheet.cell(row=row, column=col)
            cell.number_format = NUMBER_FORMAT
            cell.alignment = Alignment(horizontal="right", vertical="center")


def _finalize_sheet(
    worksheet: Worksheet,
    *,
    header_row: int,
    last_row: int,
    last_column: int,
    freeze_cell: str = "A6",
) -> None:
    worksheet.freeze_panes = freeze_cell
    worksheet.auto_filter.ref = f"A{header_row}:{get_column_letter(last_column)}{last_row}"
    worksheet.sheet_view.showGridLines = False
    worksheet.page_setup.orientation = "landscape"
    worksheet.page_setup.fitToWidth = 1
    worksheet.page_setup.fitToHeight = 0
    worksheet.sheet_properties.pageSetUpPr.fitToPage = True
    worksheet.print_title_rows = f"1:{header_row}"
    worksheet.sheet_properties.outlinePr.summaryBelow = True
    worksheet.auto_filter.ref = f"A{header_row}:{get_column_letter(last_column)}{max(last_row, header_row)}"


def write_trial_balance_sheet(workbook: Workbook, bundle: ReportBundle, sheet_name: str = "Trial Balance") -> Worksheet:
    worksheet = workbook.create_sheet(sheet_name)
    headers = [
        "Account Code",
        "Account Name",
        "Opening Balance (IDR)",
        "Opening Balance (FX)",
        "Debit-IDR",
        "Credit-IDR",
        "Debit-FX",
        "Credit-FX",
        "Ending Balance (IDR)",
        "Ending Balance (FX)",
        "Comments",
    ]
    _title_rows(worksheet, bundle, "Trial Balance / Neraca Saldo / 试算平衡表", len(headers))
    for col, header in enumerate(headers, start=1):
        worksheet.cell(row=5, column=col, value=header)
    _style_header(worksheet, 5, len(headers))

    start_row = 6
    for offset, row in enumerate(bundle.trial_balance):
        excel_row = start_row + offset
        values = [
            row.account_code,
            row.account_name,
            _num(row.opening_idr),
            _num(row.opening_fx),
            _num(row.debit_idr),
            _num(row.credit_idr),
            _num(row.debit_fx),
            _num(row.credit_fx),
            _num(row.ending_idr),
            _num(row.ending_fx),
            row.comments,
        ]
        for col, value in enumerate(values, start=1):
            cell = worksheet.cell(row=excel_row, column=col, value=safe_excel_text(value) if isinstance(value, str) else value)
            cell.font = Font(name="Aptos", size=9)
            cell.alignment = Alignment(vertical="top", wrap_text=col in {2, 11})
        worksheet.cell(excel_row, 1).number_format = "@"

    total_row = start_row + len(bundle.trial_balance)
    worksheet.cell(total_row, 1, "TOTAL")
    worksheet.cell(total_row, 2, "Rekonsiliasi")
    total_values = [
        bundle.metrics.tb_opening_idr,
        bundle.metrics.tb_opening_fx,
        bundle.metrics.journal_debit_idr,
        bundle.metrics.journal_credit_idr,
        bundle.metrics.journal_debit_fx,
        bundle.metrics.journal_credit_fx,
        bundle.metrics.tb_ending_idr,
        bundle.metrics.tb_ending_fx,
    ]
    for col, value in zip(range(3, 11), total_values):
        worksheet.cell(total_row, col, _num(value))
    for col in range(1, len(headers) + 1):
        cell = worksheet.cell(total_row, col)
        cell.font = Font(name="Aptos", size=9, bold=True, color=NAVY)
        cell.fill = PatternFill("solid", fgColor=NAVY_LIGHT)
        cell.border = Border(top=DOUBLE_NAVY)
    _apply_numeric_format(worksheet, range(start_row, total_row + 1), range(3, 11))

    widths = [16, 44, 20, 18, 18, 18, 16, 16, 20, 18, 28]
    for col, width in enumerate(widths, start=1):
        worksheet.column_dimensions[get_column_letter(col)].width = width
    _finalize_sheet(
        worksheet,
        header_row=5,
        last_row=total_row,
        last_column=len(headers),
    )
    return worksheet


def write_statement_sheet(
    workbook: Workbook,
    bundle: ReportBundle,
    rows: list[StatementRow],
    *,
    sheet_name: str,
    title: str,
    include_movement: bool,
) -> Worksheet:
    worksheet = workbook.create_sheet(sheet_name)
    headers = [
        "Code",
        "Description (Indonesia)",
        "Description (English)",
        "Description (Chinese)",
        "Opening Balance (IDR)",
    ]
    if include_movement:
        headers.append("Movement (IDR)")
    headers.append("Ending Balance (IDR)")
    _title_rows(worksheet, bundle, title, len(headers))
    for col, header in enumerate(headers, start=1):
        worksheet.cell(row=5, column=col, value=header)
    _style_header(worksheet, 5, len(headers), yellow=True)

    start_row = 6
    numeric_start = 5
    for offset, row in enumerate(rows):
        excel_row = start_row + offset
        values: list[object] = [
            row.code,
            row.description_id,
            row.description_en,
            row.description_zh,
            _num(row.opening),
        ]
        if include_movement:
            values.append(_num(row.movement))
        values.append(_num(row.ending))
        for col, value in enumerate(values, start=1):
            cell = worksheet.cell(row=excel_row, column=col, value=safe_excel_text(value) if isinstance(value, str) else value)
            cell.font = Font(name="Aptos", size=9, color=BLACK)
            cell.alignment = Alignment(vertical="center", wrap_text=col in {2, 3, 4})
        worksheet.cell(excel_row, 1).number_format = "@"
        for desc_col in (2, 3, 4):
            worksheet.cell(excel_row, desc_col).alignment = Alignment(
                vertical="center", wrap_text=True, indent=min(row.level, 2)
            )

        if row.kind == "section":
            for col in range(1, len(headers) + 1):
                cell = worksheet.cell(excel_row, col)
                cell.font = Font(name="Aptos", size=9, bold=True, color=NAVY)
                cell.fill = PatternFill("solid", fgColor=YELLOW_LIGHT)
                cell.border = Border(top=MEDIUM_NAVY)
        elif row.kind == "subtotal":
            for col in range(1, len(headers) + 1):
                cell = worksheet.cell(excel_row, col)
                cell.font = Font(name="Aptos", size=9, bold=True, color=NAVY)
                cell.border = Border(top=MEDIUM_NAVY)
        elif row.kind == "total":
            for col in range(1, len(headers) + 1):
                cell = worksheet.cell(excel_row, col)
                cell.font = Font(name="Aptos", size=9, bold=True, color=NAVY)
                cell.fill = PatternFill("solid", fgColor=NAVY_LIGHT)
                cell.border = Border(top=DOUBLE_NAVY)
        elif row.kind == "check":
            has_difference = abs(row.opening) > Decimal("0.01") or abs(row.ending) > Decimal("0.01")
            fill = ORANGE if has_difference else LIGHT_GREY
            for col in range(1, len(headers) + 1):
                cell = worksheet.cell(excel_row, col)
                cell.font = Font(name="Aptos", size=9, bold=True, color=RED if has_difference else BLACK)
                cell.fill = PatternFill("solid", fgColor=fill)
    last_row = start_row + len(rows) - 1
    _apply_numeric_format(worksheet, range(start_row, last_row + 1), range(numeric_start, len(headers) + 1))
    widths = [14, 40, 42, 36, 21, 21, 21] if include_movement else [14, 40, 42, 36, 21, 21]
    for col, width in enumerate(widths, start=1):
        worksheet.column_dimensions[get_column_letter(col)].width = width
    _finalize_sheet(
        worksheet,
        header_row=5,
        last_row=last_row,
        last_column=len(headers),
    )
    return worksheet


def write_ledger_sheet(
    workbook: Workbook,
    bundle: ReportBundle,
    rows: list[LedgerRow],
    *,
    sheet_name: str,
    title: str,
    party_label: str,
) -> Worksheet:
    worksheet = workbook.create_sheet(sheet_name)
    headers = [
        "Account Code",
        "Account Name",
        party_label,
        "Opening Balance (IDR)",
        "Opening Balance (FX)",
        "Date",
        "BL No.",
        "Remarks",
        "Description",
        "Debit-IDR",
        "Debit-FX",
        "Credit-IDR",
        "Credit-FX",
        "Ending Balance (IDR)",
        "Ending Balance (FX)",
    ]
    _title_rows(worksheet, bundle, title, len(headers))
    for col, header in enumerate(headers, start=1):
        worksheet.cell(row=5, column=col, value=header)
    _style_header(worksheet, 5, len(headers))

    start_row = 6
    for offset, row in enumerate(rows):
        excel_row = start_row + offset
        values = [
            row.account_code,
            row.account_name,
            row.party,
            _num(row.opening_idr),
            _num(row.opening_fx),
            row.transaction_date,
            row.bl_no,
            row.remarks,
            row.description,
            _num(row.debit_idr),
            _num(row.debit_fx),
            _num(row.credit_idr),
            _num(row.credit_fx),
            _num(row.ending_idr),
            _num(row.ending_fx),
        ]
        for col, value in enumerate(values, start=1):
            cell = worksheet.cell(row=excel_row, column=col, value=safe_excel_text(value) if isinstance(value, str) else value)
            cell.font = Font(name="Aptos", size=9)
            cell.alignment = Alignment(vertical="top", wrap_text=col in {2, 3, 8, 9})
        worksheet.cell(excel_row, 1).number_format = "@"
        if row.transaction_date is not None:
            worksheet.cell(excel_row, 6).number_format = DATE_FORMAT
        if row.description == "Opening Balance":
            for col in range(1, len(headers) + 1):
                cell = worksheet.cell(excel_row, col)
                cell.fill = PatternFill("solid", fgColor=NAVY_LIGHT)
                cell.font = Font(name="Aptos", size=9, bold=True, color=NAVY)
                cell.border = Border(top=MEDIUM_NAVY)
    last_row = start_row + max(len(rows), 1) - 1
    _apply_numeric_format(worksheet, range(start_row, last_row + 1), [4, 5, 10, 11, 12, 13, 14, 15])
    widths = [15, 34, 34, 20, 18, 14, 20, 32, 42, 17, 16, 17, 16, 21, 19]
    for col, width in enumerate(widths, start=1):
        worksheet.column_dimensions[get_column_letter(col)].width = width
    _finalize_sheet(
        worksheet,
        header_row=5,
        last_row=last_row,
        last_column=len(headers),
    )
    return worksheet


def write_cover_sheet(workbook: Workbook, bundle: ReportBundle, issue_counts: Counter[str]) -> Worksheet:
    worksheet = workbook.create_sheet("Cover")
    worksheet.sheet_view.showGridLines = False
    worksheet.merge_cells("A1:F2")
    worksheet["A1"] = APP_NAME
    worksheet["A1"].font = Font(name="Aptos Display", size=24, bold=True, color=WHITE)
    worksheet["A1"].fill = PatternFill("solid", fgColor=NAVY)
    worksheet["A1"].alignment = Alignment(horizontal="left", vertical="center")
    worksheet.row_dimensions[1].height = 34
    worksheet.row_dimensions[2].height = 20

    items = [
        ("Nama Klien", bundle.client_name),
        ("Periode", _period_label(bundle)),
        ("Versi aplikasi", APP_VERSION),
        ("Dibuat pada (UTC)", datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")),
        ("Error", issue_counts.get("ERROR", 0)),
        ("Warning", issue_counts.get("WARNING", 0)),
        ("Info", issue_counts.get("INFO", 0)),
    ]
    row = 4
    for label, value in items:
        worksheet.cell(row, 1, label)
        worksheet.cell(row, 2, safe_excel_text(value) if isinstance(value, str) else value)
        worksheet.cell(row, 1).font = Font(name="Aptos", size=11, bold=True, color=NAVY)
        worksheet.cell(row, 2).font = Font(name="Aptos", size=11)
        row += 1
    worksheet["A13"] = "Catatan"
    worksheet["A13"].font = Font(name="Aptos", size=11, bold=True, color=NAVY)
    worksheet.merge_cells("A14:F17")
    worksheet["A14"] = (
        "Workbook ini berisi laporan hasil pemrosesan otomatis. Periksa sheet Validation Summary dan Issues "
        "sebelum laporan digunakan untuk pelaporan resmi. Akun yang belum dipetakan tetap dicatat di Trial Balance "
        "dan disajikan pada kelompok khusus agar transaksi tidak hilang."
    )
    worksheet["A14"].alignment = Alignment(wrap_text=True, vertical="top")
    worksheet["A14"].fill = PatternFill("solid", fgColor=YELLOW_LIGHT)
    worksheet.column_dimensions["A"].width = 24
    worksheet.column_dimensions["B"].width = 42
    for col in range(3, 7):
        worksheet.column_dimensions[get_column_letter(col)].width = 15
    return worksheet


def write_validation_sheets(workbook: Workbook, bundle: ReportBundle) -> list[Worksheet]:
    worksheets: list[Worksheet] = []
    issue_counts = Counter(issue.severity for issue in bundle.issues)
    summary = workbook.create_sheet("Validation Summary")
    worksheets.append(summary)
    summary.sheet_view.showGridLines = False
    summary.merge_cells("A1:D1")
    summary["A1"] = "Validation Summary"
    summary["A1"].font = Font(name="Aptos Display", size=18, bold=True, color=WHITE)
    summary["A1"].fill = PatternFill("solid", fgColor=NAVY)
    summary["A1"].alignment = Alignment(horizontal="left")
    summary.append([])
    summary.append(["Metric", "Value", "Tolerance / Status", "Notes"])
    _style_header(summary, 3, 4)

    metric_rows = [
        ("Journal rows read", bundle.metrics.journal_rows_read, "", ""),
        ("Journal rows used", bundle.metrics.journal_rows_used, "", "Within selected period"),
        ("Journal rows outside period", bundle.metrics.journal_rows_outside_period, "", "Excluded"),
        ("Journal debit IDR", _num(bundle.metrics.journal_debit_idr), "", ""),
        ("Journal credit IDR", _num(bundle.metrics.journal_credit_idr), "", ""),
        (
            "Journal difference IDR",
            _num(bundle.metrics.journal_debit_idr - bundle.metrics.journal_credit_idr),
            "0.01",
            "Must be near zero",
        ),
        ("TB opening difference IDR", _num(bundle.metrics.tb_opening_idr), "0.01", "Must be near zero"),
        ("TB ending difference IDR", _num(bundle.metrics.tb_ending_idr), "0.01", "Must be near zero"),
        ("Balance Sheet opening difference", _num(bundle.metrics.bs_difference_opening), "0.01", "Assets - L&E"),
        ("Balance Sheet ending difference", _num(bundle.metrics.bs_difference_ending), "0.01", "Assets - L&E"),
        (
            "Cash beginning reconciliation",
            _num(bundle.metrics.cash_reconciliation_opening),
            "0.01",
            "Cash Flow - TB cash/bank",
        ),
        (
            "Cash ending reconciliation",
            _num(bundle.metrics.cash_reconciliation_ending),
            "0.01",
            "Cash Flow - TB cash/bank",
        ),
        ("Earnings after tax", _num(bundle.metrics.earnings_after_tax_ending), "", "Income Statement"),
        ("Errors", issue_counts.get("ERROR", 0), "0", ""),
        ("Warnings", issue_counts.get("WARNING", 0), "Review", ""),
        ("Info", issue_counts.get("INFO", 0), "", ""),
    ]
    for values in metric_rows:
        summary.append(values)
    for row in range(4, 4 + len(metric_rows)):
        summary.cell(row, 2).number_format = NUMBER_FORMAT
        summary.cell(row, 1).font = Font(name="Aptos", size=10, bold=True if "difference" in str(summary.cell(row, 1).value).lower() else False)
        for col in range(1, 5):
            summary.cell(row, col).border = Border(bottom=Side(style="hair", color="D9E2F3"))
    for col, width in enumerate([38, 24, 20, 42], start=1):
        summary.column_dimensions[get_column_letter(col)].width = width
    summary.freeze_panes = "A4"

    issues_sheet = workbook.create_sheet("Issues")
    worksheets.append(issues_sheet)
    issue_headers = ["Severity", "Category", "Reference", "Message"]
    issues_sheet.append(issue_headers)
    _style_header(issues_sheet, 1, len(issue_headers))
    for issue in bundle.issues:
        issues_sheet.append([issue.severity, issue.category, issue.reference, safe_excel_text(issue.message)])
        row = issues_sheet.max_row
        fill = {"ERROR": "F4CCCC", "WARNING": "FCE5CD", "INFO": "D9EAF7"}.get(issue.severity, WHITE)
        for col in range(1, 5):
            issues_sheet.cell(row, col).fill = PatternFill("solid", fgColor=fill)
            issues_sheet.cell(row, col).alignment = Alignment(vertical="top", wrap_text=True)
        issues_sheet.cell(row, 1).font = Font(bold=True, color=RED if issue.severity == "ERROR" else BLACK)
    for col, width in enumerate([12, 24, 30, 90], start=1):
        issues_sheet.column_dimensions[get_column_letter(col)].width = width
    issues_sheet.freeze_panes = "A2"
    issues_sheet.auto_filter.ref = f"A1:D{max(issues_sheet.max_row, 1)}"
    issues_sheet.sheet_view.showGridLines = False

    voucher_sheet = workbook.create_sheet("Voucher Reconciliation")
    worksheets.append(voucher_sheet)
    voucher_headers = [
        "Voucher No.",
        "Debit IDR",
        "Credit IDR",
        "Difference IDR",
        "Debit FX",
        "Credit FX",
        "Difference FX",
        "Status IDR",
    ]
    voucher_sheet.append(voucher_headers)
    _style_header(voucher_sheet, 1, len(voucher_headers))
    for item in bundle.voucher_reconciliation:
        status = "OK" if abs(item.difference_idr) <= Decimal("0.01") else "NOT BALANCED"
        voucher_sheet.append(
            [
                safe_excel_text(item.voucher_no),
                _num(item.debit_idr),
                _num(item.credit_idr),
                _num(item.difference_idr),
                _num(item.debit_fx),
                _num(item.credit_fx),
                _num(item.difference_fx),
                status,
            ]
        )
    _apply_numeric_format(voucher_sheet, range(2, voucher_sheet.max_row + 1), range(2, 8))
    for col, width in enumerate([22, 20, 20, 18, 18, 18, 18, 16], start=1):
        voucher_sheet.column_dimensions[get_column_letter(col)].width = width
    voucher_sheet.freeze_panes = "A2"
    voucher_sheet.auto_filter.ref = f"A1:H{max(voucher_sheet.max_row, 1)}"
    voucher_sheet.sheet_view.showGridLines = False

    unmapped_sheet = workbook.create_sheet("Unmapped Accounts")
    worksheets.append(unmapped_sheet)
    unmapped_headers = [
        "Account Code",
        "Account Name",
        "Opening IDR",
        "Debit IDR",
        "Credit IDR",
        "Ending IDR",
        "Suggested Action",
    ]
    unmapped_sheet.append(unmapped_headers)
    _style_header(unmapped_sheet, 1, len(unmapped_headers))
    for item in bundle.unmapped_accounts:
        unmapped_sheet.append(
            [
                safe_excel_text(item.account_code),
                safe_excel_text(item.account_name),
                _num(item.opening_idr),
                _num(item.debit_idr),
                _num(item.credit_idr),
                _num(item.ending_idr),
                "Add account and BS/IS classification to COA Master",
            ]
        )
    _apply_numeric_format(unmapped_sheet, range(2, unmapped_sheet.max_row + 1), range(3, 7))
    for col, width in enumerate([18, 42, 20, 18, 18, 20, 50], start=1):
        unmapped_sheet.column_dimensions[get_column_letter(col)].width = width
    unmapped_sheet.freeze_panes = "A2"
    unmapped_sheet.auto_filter.ref = f"A1:G{max(unmapped_sheet.max_row, 1)}"
    unmapped_sheet.sheet_view.showGridLines = False

    mapping_sheet = workbook.create_sheet("Cash Flow Mapping")
    worksheets.append(mapping_sheet)
    mapping_headers = [
        "Journal Row",
        "Voucher No.",
        "Source Code",
        "Mapped Code",
        "Method",
        "Amount IDR",
        "Status",
    ]
    mapping_sheet.append(mapping_headers)
    _style_header(mapping_sheet, 1, len(mapping_headers))
    for item in bundle.cash_flow_mapping_audit:
        mapping_sheet.append(
            [
                item.journal_row,
                safe_excel_text(item.voucher_no),
                safe_excel_text(item.source_code),
                safe_excel_text(item.mapped_code),
                item.method,
                _num(item.amount),
                item.status,
            ]
        )
    _apply_numeric_format(mapping_sheet, range(2, mapping_sheet.max_row + 1), [6])
    for col, width in enumerate([14, 22, 16, 16, 22, 20, 16], start=1):
        mapping_sheet.column_dimensions[get_column_letter(col)].width = width
    mapping_sheet.freeze_panes = "A2"
    mapping_sheet.auto_filter.ref = f"A1:G{max(mapping_sheet.max_row, 1)}"
    mapping_sheet.sheet_view.showGridLines = False
    return worksheets


def _new_workbook(title: str) -> Workbook:
    workbook = Workbook()
    workbook.remove(workbook.active)
    _set_document_properties(workbook, title)
    return workbook


def _save_single_report(path: Path, title: str, writer: Callable[[Workbook], Worksheet]) -> None:
    workbook = _new_workbook(title)
    writer(workbook)
    workbook.active = 0
    workbook.save(path)


def generate_report_package(bundle: ReportBundle, output_dir: str | Path) -> GenerationResult:
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    issue_counts = Counter(issue.severity for issue in bundle.issues)

    files: list[Path] = []
    report_specs: list[tuple[str, str, Callable[[Workbook], Worksheet]]] = [
        (
            "01_Trial_Balance.xlsx",
            "Trial Balance",
            lambda wb: write_trial_balance_sheet(wb, bundle),
        ),
        (
            "02_Income_Statement.xlsx",
            "Income Statement",
            lambda wb: write_statement_sheet(
                wb,
                bundle,
                bundle.income_statement,
                sheet_name="Income Statement",
                title="Laporan Laba Rugi / Income Statement / 损益表",
                include_movement=True,
            ),
        ),
        (
            "03_Balance_Sheet.xlsx",
            "Balance Sheet",
            lambda wb: write_statement_sheet(
                wb,
                bundle,
                bundle.balance_sheet,
                sheet_name="Balance Sheet",
                title="Laporan Posisi Keuangan / Balance Sheet / 资产负债表",
                include_movement=False,
            ),
        ),
        (
            "04_Cash_Flow_Statement.xlsx",
            "Cash Flow Statement",
            lambda wb: write_statement_sheet(
                wb,
                bundle,
                bundle.cash_flow,
                sheet_name="Cash Flow",
                title="Laporan Arus Kas / Cash Flow Statement / 现金流量表",
                include_movement=True,
            ),
        ),
        (
            "05_AR_Report.xlsx",
            "Accounts Receivable Report",
            lambda wb: write_ledger_sheet(
                wb,
                bundle,
                bundle.ar_ledger,
                sheet_name="AR Report",
                title="Laporan Piutang Usaha / Accounts Receivable Report / 应收账款报表",
                party_label="Customer",
            ),
        ),
        (
            "06_AP_Report.xlsx",
            "Accounts Payable Report",
            lambda wb: write_ledger_sheet(
                wb,
                bundle,
                bundle.ap_ledger,
                sheet_name="AP Report",
                title="Laporan Utang Usaha / Accounts Payable Report / 应付账款报表",
                party_label="Vendor",
            ),
        ),
        (
            "07_Advance_Payment_Report.xlsx",
            "Advance Payment Report",
            lambda wb: write_ledger_sheet(
                wb,
                bundle,
                bundle.advance_ledger,
                sheet_name="Advance Payment",
                title="Laporan Advance Payment / Advance Payment Report / 预付款报告",
                party_label="Vendor",
            ),
        ),
    ]

    for filename, title, writer in report_specs:
        path = output_dir / filename
        _save_single_report(path, title, writer)
        files.append(path)

    validation_path = output_dir / "08_Validation_Summary.xlsx"
    validation_wb = _new_workbook("Validation Summary")
    write_validation_sheets(validation_wb, bundle)
    validation_wb.active = 0
    validation_wb.save(validation_path)
    files.append(validation_path)

    consolidated_path = output_dir / "All_Reports.xlsx"
    consolidated = _new_workbook("All Reports")
    write_cover_sheet(consolidated, bundle, issue_counts)
    write_trial_balance_sheet(consolidated, bundle)
    write_statement_sheet(
        consolidated,
        bundle,
        bundle.income_statement,
        sheet_name="Income Statement",
        title="Laporan Laba Rugi / Income Statement / 损益表",
        include_movement=True,
    )
    write_statement_sheet(
        consolidated,
        bundle,
        bundle.balance_sheet,
        sheet_name="Balance Sheet",
        title="Laporan Posisi Keuangan / Balance Sheet / 资产负债表",
        include_movement=False,
    )
    write_statement_sheet(
        consolidated,
        bundle,
        bundle.cash_flow,
        sheet_name="Cash Flow",
        title="Laporan Arus Kas / Cash Flow Statement / 现金流量表",
        include_movement=True,
    )
    write_ledger_sheet(
        consolidated,
        bundle,
        bundle.ar_ledger,
        sheet_name="AR Report",
        title="Laporan Piutang Usaha / Accounts Receivable Report / 应收账款报表",
        party_label="Customer",
    )
    write_ledger_sheet(
        consolidated,
        bundle,
        bundle.ap_ledger,
        sheet_name="AP Report",
        title="Laporan Utang Usaha / Accounts Payable Report / 应付账款报表",
        party_label="Vendor",
    )
    write_ledger_sheet(
        consolidated,
        bundle,
        bundle.advance_ledger,
        sheet_name="Advance Payment",
        title="Laporan Advance Payment / Advance Payment Report / 预付款报告",
        party_label="Vendor",
    )
    write_validation_sheets(consolidated, bundle)
    consolidated.active = 0
    consolidated.save(consolidated_path)
    files.append(consolidated_path)

    manifest = {
        "application": APP_NAME,
        "version": APP_VERSION,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "client_name": bundle.client_name,
        "period_start": bundle.period_start.isoformat(),
        "period_end": bundle.period_end.isoformat(),
        "inputs": bundle.input_hashes,
        "outputs": [path.name for path in files],
        "issue_counts": dict(issue_counts),
        "notes": [
            "Account codes missing from COA are retained in Trial Balance and listed in Validation Summary.",
            "Sequential cash-flow codes are mapped to Cash Flow Master item order.",
        ],
    }
    manifest_path = output_dir / "processing_manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    files.append(manifest_path)

    zip_name = (
        f"lapkeu_{slugify(bundle.client_name)}_"
        f"{bundle.period_start.strftime('%Y%m%d')}_{bundle.period_end.strftime('%Y%m%d')}.zip"
    )
    zip_path = output_dir / zip_name
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        for path in files:
            archive.write(path, arcname=path.name)
    return GenerationResult(
        zip_path=zip_path,
        output_files=[path.name for path in files],
        issue_counts={key: issue_counts.get(key, 0) for key in ("ERROR", "WARNING", "INFO")},
    )
