JAZZMIN_SETTINGS = {
    "site_title": "Amytang Workspace",
    "site_header": "Automation",
    "site_brand": "Amytang",
    "welcome_sign": "Amytang Workspace",
    "copyright": "PT Amytang Consulting",
    "show_ui_builder": False,
    "navigation_expanded": True,
    "show_sidebar": True,
    "topmenu_links": [
        {"name": "ERP Home", "url": "admin:index"},
        {"name": "API Docs", "url": "/docs/", "new_window": True},
        {"name": "Health", "url": "/health/", "new_window": True},
    ],
    "icons": {
        "accounts.User": "fas fa-users-cog",
        "auth.Group": "fas fa-user-tag",
        "depreciation.DepreciationWorkspace": "fas fa-chart-line",
        "financial_reporting.FinancialReportingWorkspace": "fas fa-file-invoice-dollar",
        "tax_review.TaxReviewWorkspace": "fas fa-calulator",

    },
    "custom_links": {},
    "order_with_respect_to": [
        "depreciation",
        "depreciation.DepreciationWorkspace",
        "financial_reporting",
        "financial_reporting.GenerateFinancialReportWorkspace",
        "financial_reporting.DepreciationScheduleWorkspace",
        "financial_reporting.BankStatementWorkspace",
        "tax_review",
        "accounts",
        # "tax_review",
        # "tax_review.TaxReviewWorkspace",
        # "accounts",
        "accounts.User",
        "auth",
        "auth.Group",
    ],
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
    "dark_mode_theme": "darkly",
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
}
