# Generated by Django 5.1.15 on 2026-09-02 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('depreciation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depreciationworkspace',
            options={'default_permissions': (), 'managed': False, 'verbose_name': 'Depreciation Schedule', 'verbose_name_plural': 'Depreciation Schedule'},
        ),
    ]
