# Generated by Django 5.1.15 on 2026-09-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReviewWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Review Pajak',
                'verbose_name_plural': 'Review Pajak',
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
